[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mortimer"
dynamic = ["version"]
description = "A web-appication for the administration of alfred experiments."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.13"
license = { text = "MIT" }
authors = [
  { name = "Christian Treffenstädt" },
  { name = "Paul Wiemann" },
  { name = "Johannes Brachem", email = "alfred@psych.uni-goettingen.de" },
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "alfred3>=2.0.0",
  "alfred3_interact>=0.2.4",
  "cryptography>=3.4",
  "email_validator>=1.1",
  "itsdangerous>=2.1.2",
  "flask>=1.1.2",
  "flask_bcrypt>=0.7.1",
  "flask_dropzone>=1.5.4",
  "flask_login>=0.5.0",
  "flask_mail>=0.9.1",
  "flask-wtf>=0.14.3",
  "pymongo>=3.10",
  "python-dotenv",
  "flask-mongoengine-3[wtf]>=1.1.0",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pre-commit",
  "black",
  "flake8",
  "python-dotenv",
  "bs4",
  "mongomock",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.dynamic]
version = { attr = "mortimer._version.__version__" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["mortimer*"]

[tool.setuptools.package-data]
"mortimer" = [
  "static/*",
  "static/futurizing_alfred_scripts/*",
  "static/css/*",
  "static/img/*",
  "static/js/*",
  "static/json/*",
  "templates/*",
  "templates/elements/*",
  "templates/errors/*",
  "templates/additional/*",
]

[tool.uv]
dev-dependencies = ["mortimer[dev]"]
